name: Deploy
on:
    push:
        branches:
            - master
jobs:
    build:
        name: Prepare environment, build and deploy
        runs-on: ubuntu-latest
        steps:
#             -   name: Set Permissions
#                 uses: fifsky/ssh-action@master
#                 with:
#                     command: |
#                         sudo chown $USER:www-data -R /var/www/html
#                     host: 54.221.185.84
#                     user: ubuntu
#                     key: ${{ secrets.SERVER_KEY }}

            -   name: Clone the repository
                uses: actions/checkout@master
                
#             -   name: Install PHP
#                 uses: shivammathur/setup-php@v2
#                 with:
#                     php-version: '8.0'

#             -   name: Create build folder
#                 run: mkdir /home/runner/work/API_Hacienda/API_Hacienda/

            -   name: Check current folder
                run: pwd
            
            # -   name: List current folders
            #     run: ls
                

                 
            # -   name: Check current folder
            #     run: pwd

            # -   name: Copy app folder to the new build
            #     run: cp -r app /home/runner/work/API_Hacienda/API_Hacienda/build
                
            # -   name: Copy bootstrap folder to the new build
            #     run: cp -r bootstrap /home/runner/work/API_Hacienda/API_Hacienda/build

            -   name: Deploy api.php file
                uses: burnett01/rsync-deployments@5.1
                with:
                    switches: -avzr --delete --verbose
                    path: ./www/api.php
                    remote_path: /var/www/html
                    remote_host: 54.221.185.84
                    remote_port: 22
                    remote_user: ubuntu
                    remote_key: ${{ secrets.SERVER_KEY }}

            -   name: Deploy index.php file
                uses: burnett01/rsync-deployments@5.1
                with:
                    switches: -avzr --delete --verbose
                    path: ./www/index.php
                    remote_path: /var/www/html
                    remote_host: 54.221.185.84
                    remote_port: 22
                    remote_user: ubuntu
                    remote_key: ${{ secrets.SERVER_KEY }}
                    
                    
            -   name: Deploy index.php file
                uses: burnett01/rsync-deployments@5.1
                with:
                    switches: -avzr --delete --verbose
                    path: ./www/settings.php
                    remote_path: /var/www/
                    remote_host: 54.221.185.84
                    remote_port: 22
                    remote_user: ubuntu
                    remote_key: ${{ secrets.SERVER_KEY }}
                    
